addons:
  sonarcloud:
    organization: "arnaud80"
    token:
      secure: "k0EZg7OKtgH8qNqvYB8RbBqUGIoV6QM+lcO+0+JWtzX8IJvknLGGlAdCt+GMAA0iX9eJ+3Hm3f8JTL3cto+kXYbCoA4u+nHQjCpaAERiD3/BbcA84QDvCPPg74xLV6b9a4RsKFLLaPSgqhz98LPMwot5QJ9bPDU9545qU8iXXGAA/Q2ARXEYeqr9bokuOGJRbV9JIPYdgW+2KGdLFjbIhf0Pa+OXvu5hRR7GiDPn33nbY/uCwPeXuWk9F3mi7nSq8UAAv3SLCT6TyMxff+DhYBgYeYSG8eUe4mkiQh2T1c+4eFK8t0Ggxtv6haikW7bCQkxA84jl5O4gflD+zyCPWyf6KReKq24vbnupU2GzJw/6kV1/Uaq6S/vQE4NFPSxsNL1acvyzsgwQ1fvuBaOULRY0MRzf0oQgLWBzK4tmZGUuh2UJ1B9AwBu07xvPYm1a7NexVUmhHhGl7vg5i62QHCUNW62mdO1Xn1BZSy6aR03XpXrjULiBfOt56FL8qtG9raORrVyn4rBrGEF0C0DDJUUNUN38RsQOcePzM4y1W7pEHVLXkmpm0hTWVkvNGplI/NKqhqgJbxnzj5NeSJlgqkg9XtJqI68/nBjdhYq6+gewuk9hujxPmMeiIIsP2JpIcSp9AwVgwhgtR2wQUaiOH5V2VcJ2W4EkRIeNKe/0jnU="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner

addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk: openjdk6
